#!/bin/bash
#SBATCH --requeue
#SBATCH --job-name=LampSegmentation

#SBATCH --nodes=1
#SBATCH --cpus-per-gpu=16
#SBATCH --gpus=1
#SBATCH --mem=32GB

#SBATCH --partition=submit
#SBATCH --qos=deadline

#SBATCH --signal=2

#SBATCH --output=/cluster/valinor/pkocsis/projects/relighting/logs/geometry_%j.log
#SBATCH --open-mode=append

#SBATCH --time=4-00:00:00

#SBATCH --mail-type=ALL
#SBATCH --mail-user=peter.kocsis@tum.de


export PYTHONUNBUFFERED="True"

python -m main $SCRIPT_ARGUMENTS
